// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClcPZjz93AD2qr-lYpJFvXXG04p7oOY9k',
    appId: '1:41447095843:web:09cd052a2f6dcc815d7b96',
    messagingSenderId: '41447095843',
    projectId: 'srivats-22',
    authDomain: 'srivats-22.firebaseapp.com',
    databaseURL: 'https://srivats-22.firebaseio.com',
    storageBucket: 'srivats-22.appspot.com',
    measurementId: 'G-Q4DC8CKB44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1UmGAvvfRNYga_nv-mQEHrN4Idr-jH3w',
    appId: '1:41447095843:android:770494941f8a10ee5d7b96',
    messagingSenderId: '41447095843',
    projectId: 'srivats-22',
    databaseURL: 'https://srivats-22.firebaseio.com',
    storageBucket: 'srivats-22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaokyNcUz9y_LEAbzAtcQOAEPUvCd811c',
    appId: '1:41447095843:ios:2c4dd87dc583429a5d7b96',
    messagingSenderId: '41447095843',
    projectId: 'srivats-22',
    databaseURL: 'https://srivats-22.firebaseio.com',
    storageBucket: 'srivats-22.appspot.com',
    iosClientId: '41447095843-36plhdpaqc3gsd5hf4027ab8m0m5j8ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
